- name: Install zsh, git, wget
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - git
    - wget
    - autojump
    - peco

- name: Clone antigen
  git:
    repo: https://github.com/zsh-users/antigen.git
    dest: "~{{ zsh_user }}/.antigen.repo"
    version: "master"
    force: yes
  become: yes
  become_user: "{{ zsh_user }}"
  register: zsh_register_antigen_clone

- name: Write .zshrc config
  template:
    src: zshrc.j2
    dest: "~{{ zsh_user }}/.zshrc"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"
    backup: yes

- name: Set zsh as default shell
  user:
    name: "{{ zsh_user }}"
    shell: /bin/zsh
  become: true

- name: Write autoenv.sh
  template:
    src: autoenv.sh.j2
    dest: "~{{ zsh_user }}/.autoenv.sh"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"

- name: Write zshrc.local
  template:
    src: zshrc.local.j2
    dest: "~{{ zsh_user }}/.zshrc.local"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"
    backup: yes

- name: Write gitconfig
  template:
    src: gitconfig.j2
    dest: "~{{ zsh_user }}/.gitconfig"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"

- include_tasks: vim.yml

- include_tasks: bat.yml